version: "3"

services:
  backend:
      build: dp
      container_name: backend-container
  shop:
    image: nginx
    container_name: frontend-shop-container
    ports:
      - 81:80
    depends_on:
      - nginx
    volumes:
      - ./scripts/front-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
  nginx:
    image: nginx
    container_name: nginx-container
    ports: 
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx


