version: "3"

services:
  backend:
      build: dp
      container_name: backend-container
  nginx:
    image: nginx
    container_name: frontend-customer-container
    ports: 
      - 80:80
    depends_on:
      - backend
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx


