version: "3"

services:
  backend:
    image: kangmin46/backend
    container_name: backend-container
    networks:
      - app-net
  shop:
    image: kangmin46/frontend-shop
    container_name: frontend-shop-container
    ports:
      - 81:80
    volumes:
      - ./scripts/front-shop-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    networks:
      - app-net
  customer:
    image: kangmin46/frontend-customer
    container_name: frontend-customer-container
    ports:
      - 82:80
    volumes:
      - ./scripts/front-customer-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
      networks:
        - app-net
  nginx:
    image: nginx
    container_name: nginx-container
    ports: 
      - 80:80
    depends_on:
      - backend
      - shop
      - customer
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    networks:
      - app-net

networks:
  app-net:


