version: "3"

services:
  backend:
    build: dp
    container_name: backend-container
    networks:
      - app-net
  shop:
    image: nginx
    container_name: frontend-shop-container
    ports:
      - 81:80
    depends_on:
      - nginx
    volumes:
      - ./scripts/front-customer-nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
      - ./caffein-fe-shop:/usr/src/app/public
    networks:
      - app-net
  nginx:
    image: nginx
    container_name: nginx-container
    ports: 
      - 80:80
    depends_on:
      - backend
      - shop
    volumes:
      - ./scripts/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/log:/var/log/nginx
    networks:
      - app-net

networks:
  app-net:


